name: shop_maternityapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  file_picker: ^9.0.2
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.3.1
  pdf: ^3.11.3
  printing: ^5.14.2
  supabase_flutter: ^2.8.3
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - Assets/
